<a href="https://colab.research.google.com/github/empatiharshit28-cyber/Data_Analytics/blob/main/da_asingment_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dataset=pd.read_csv('/content/student_probability_dataset (1) - student_probability_dataset (1).csv')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      120 non-null    int64
 1   Gender          120 non-null    object
 2   Study_Hours     120 non-null    int64
 3   Attendance      120 non-null    int64
 4   Previous_Score  120 non-null    int64
 5   Result          120 non-null    object
dtypes: int64(4), object(2)
memory usage: 5.8+ KB

In [ ]:
dataset.isnull().sum()

Student_ID        0
Gender            0
Study_Hours       0
Attendance        0
Previous_Score    0
Result            0
dtype: int64

In [ ]:
dataset.describe()

       Student_ID  Study_Hours  Attendance  Previous_Score
count  120.000000   120.000000  120.000000      120.000000
mean    60.500000     3.375000   73.350000       67.933333
std     34.785054     1.729927   14.843526       14.137223
min      1.000000     1.000000   50.000000       40.000000
25%     30.750000     2.000000   60.000000       59.750000
50%     60.500000     3.000000   73.500000       69.000000
75%     90.250000     5.000000   85.000000       80.250000
max    120.000000     6.000000   99.000000       90.000000

In [ ]:
dataset.head()

   Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
0           1    Male            5          88              56   Fail
1           2  Female            2          51              72   Fail
2           3    Male            5          52              87   Fail
3           4    Male            2          98              51   Fail
4           5    Male            1          86              90   Fail

In [ ]:

dataset.tail()

     Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
115         116  Female            1          97              83   Fail
116         117    Male            2          69              83   Fail
117         118  Female            4          57              44   Fail
118         119  Female            4          56              78   Fail
119         120    Male            6          52              43   Fail

In [ ]:
dataset[dataset['Gender'] == 'Male']

     Student_ID Gender  Study_Hours  Attendance  Previous_Score Result
0             1   Male            5          88              56   Fail
2             3   Male            5          52              87   Fail
3             4   Male            2          98              51   Fail
4             5   Male            1          86              90   Fail
6             7   Male            4          66              61   Fail
7             8   Male            4          98              85   Pass
8             9   Male            5          51              69   Fail
10           11   Male            5          77              77   Pass
11           12   Male            5          72              84   Pass
12           13   Male            1          86              90   Fail
13           14   Male            1          81              47   Fail
15           16   Male            1          50              66   Fail
19           20   Male            1          75              72   Fail
21           22   Male            3          55              86   Fail
30           31   Male            4          55              83   Fail
31           32   Male            2          71              67   Fail
35           36   Male            3          82              45   Fail
37           38   Male            6          55              80   Fail
38           39   Male            3          65              76   Fail
39           40   Male            3          78              63   Fail
40           41   Male            1          52              68   Fail
41           42   Male            3          69              88   Fail
47           48   Male            2          69              71   Fail
50           51   Male            1          90              42   Fail
52           53   Male            2          89              64   Fail
54           55   Male            5          67              70   Fail
57           58   Male            4          60              85   Fail
58           59   Male            5          77              63   Pass
59           60   Male            4          74              89   Pass
60           61   Male            6          99              71   Pass
61           62   Male            5          72              86   Pass
62           63   Male            5          80              61   Pass
63           64   Male            3          79              62   Fail
64           65   Male            5          91              41   Fail
67           68   Male            3          65              41   Fail
72           73   Male            2          50              48   Fail
74           75   Male            6          61              87   Fail
78           79   Male            4          58              65   Fail
80           81   Male            4          84              89   Pass
82           83   Male            4          97              63   Pass
84           85   Male            6          52              46   Fail
85           86   Male            3          69              75   Fail
87           88   Male            4          82              59   Fail
99          100   Male            3          84              41   Fail
100         101   Male            6          74              71   Pass
109         110   Male            3          85              45   Fail
111         112   Male            1          53              82   Fail
114         115   Male            6          70              47   Fail
116         117   Male            2          69              83   Fail
119         120   Male            6          52              43   Fail

In [ ]:
dataset[dataset['Result'] == 'Pass']

     Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
5             6  Female            4          98              61   Pass
7             8    Male            4          98              85   Pass
10           11    Male            5          77              77   Pass
11           12    Male            5          72              84   Pass
33           34  Female            6          97              68   Pass
42           43  Female            5          85              85   Pass
48           49  Female            6          81              62   Pass
53           54  Female            4          88              81   Pass
58           59    Male            5          77              63   Pass
59           60    Male            4          74              89   Pass
60           61    Male            6          99              71   Pass
61           62    Male            5          72              86   Pass
62           63    Male            5          80              61   Pass
65           66  Female            4          84              66   Pass
70           71  Female            4          98              79   Pass
73           74  Female            5          97              82   Pass
76           77  Female            5          86              68   Pass
77           78  Female            6          81              81   Pass
79           80  Female            4          90              74   Pass
80           81    Male            4          84              89   Pass
82           83    Male            4          97              63   Pass
94           95  Female            6          89              90   Pass
97           98  Female            5          97              67   Pass
100         101    Male            6          74              71   Pass
103         104  Female            6          95              90   Pass
108         109  Female            4          90              81   Pass
112         113  Female            4          82              76   Pass

In [ ]:
dataset[dataset['Attendance']>75]

     Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
0             1    Male            5          88              56   Fail
3             4    Male            2          98              51   Fail
4             5    Male            1          86              90   Fail
5             6  Female            4          98              61   Pass
7             8    Male            4          98              85   Pass
10           11    Male            5          77              77   Pass
12           13    Male            1          86              90   Fail
13           14    Male            1          81              47   Fail
14           15  Female            1          82              66   Fail
18           19  Female            3          93              69   Fail
20           21  Female            3          81              67   Fail
22           23  Female            1          81              72   Fail
26           27  Female            2          87              43   Fail
29           30  Female            1          83              56   Fail
33           34  Female            6          97              68   Pass
35           36    Male            3          82              45   Fail
39           40    Male            3          78              63   Fail
42           43  Female            5          85              85   Pass
48           49  Female            6          81              62   Pass
50           51    Male            1          90              42   Fail
51           52  Female            2          82              57   Fail
52           53    Male            2          89              64   Fail
53           54  Female            4          88              81   Pass
55           56  Female            3          89              42   Fail
58           59    Male            5          77              63   Pass
60           61    Male            6          99              71   Pass
62           63    Male            5          80              61   Pass
63           64    Male            3          79              62   Fail
64           65    Male            5          91              41   Fail
65           66  Female            4          84              66   Pass
69           70  Female            6          97              56   Fail
70           71  Female            4          98              79   Pass
73           74  Female            5          97              82   Pass
76           77  Female            5          86              68   Pass
77           78  Female            6          81              81   Pass
79           80  Female            4          90              74   Pass
80           81    Male            4          84              89   Pass
82           83    Male            4          97              63   Pass
87           88    Male            4          82              59   Fail
90           91  Female            1          98              85   Fail
92           93  Female            1          85              53   Fail
93           94  Female            3          87              51   Fail
94           95  Female            6          89              90   Pass
96           97  Female            4          84              54   Fail
97           98  Female            5          97              67   Pass
99          100    Male            3          84              41   Fail
101         102  Female            3          78              62   Fail
103         104  Female            6          95              90   Pass
106         107  Female            3          84              61   Fail
108         109  Female            4          90              81   Pass
109         110    Male            3          85              45   Fail
110         111  Female            6          82              54   Fail
112         113  Female            4          82              76   Pass
115         116  Female            1          97              83   Fail

In [ ]:
dataset[dataset['Previous_Score']>70]

     Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
1             2  Female            2          51              72   Fail
2             3    Male            5          52              87   Fail
4             5    Male            1          86              90   Fail
7             8    Male            4          98              85   Pass
9            10  Female            1          51              77   Fail
10           11    Male            5          77              77   Pass
11           12    Male            5          72              84   Pass
12           13    Male            1          86              90   Fail
16           17  Female            4          68              73   Fail
19           20    Male            1          75              72   Fail
21           22    Male            3          55              86   Fail
22           23  Female            1          81              72   Fail
24           25  Female            5          60              87   Fail
27           28  Female            1          73              74   Fail
28           29  Female            4          54              88   Fail
30           31    Male            4          55              83   Fail
34           35  Female            5          65              85   Fail
36           37  Female            4          58              74   Fail
37           38    Male            6          55              80   Fail
38           39    Male            3          65              76   Fail
41           42    Male            3          69              88   Fail
42           43  Female            5          85              85   Pass
44           45  Female            3          75              74   Fail
45           46  Female            1          52              72   Fail
47           48    Male            2          69              71   Fail
49           50  Female            3          56              72   Fail
53           54  Female            4          88              81   Pass
56           57  Female            1          50              79   Fail
57           58    Male            4          60              85   Fail
59           60    Male            4          74              89   Pass
60           61    Male            6          99              71   Pass
61           62    Male            5          72              86   Pass
66           67  Female            5          56              81   Fail
70           71  Female            4          98              79   Pass
71           72  Female            2          51              72   Fail
73           74  Female            5          97              82   Pass
74           75    Male            6          61              87   Fail
75           76  Female            1          54              78   Fail
77           78  Female            6          81              81   Pass
79           80  Female            4          90              74   Pass
80           81    Male            4          84              89   Pass
85           86    Male            3          69              75   Fail
86           87  Female            2          73              84   Fail
90           91  Female            1          98              85   Fail
94           95  Female            6          89              90   Pass
98           99  Female            1          74              73   Fail
100         101    Male            6          74              71   Pass
103         104  Female            6          95              90   Pass
107         108  Female            2          65              88   Fail
108         109  Female            4          90              81   Pass
111         112    Male            1          53              82   Fail
112         113  Female            4          82              76   Pass
113         114  Female            1          63              72   Fail
115         116  Female            1          97              83   Fail
116         117    Male            2          69              83   Fail
118         119  Female            4          56              78   Fail

In [ ]:
dataset[dataset['Study_Hours'] > 4]

     Student_ID  Gender  Study_Hours  Attendance  Previous_Score Result
0             1    Male            5          88              56   Fail
2             3    Male            5          52              87   Fail
8             9    Male            5          51              69   Fail
10           11    Male            5          77              77   Pass
11           12    Male            5          72              84   Pass
24           25  Female            5          60              87   Fail
33           34  Female            6          97              68   Pass
34           35  Female            5          65              85   Fail
37           38    Male            6          55              80   Fail
42           43  Female            5          85              85   Pass
43           44  Female            6          68              70   Fail
46           47  Female            5          68              60   Fail
48           49  Female            6          81              62   Pass
54           55    Male            5          67              70   Fail
58           59    Male            5          77              63   Pass
60           61    Male            6          99              71   Pass
61           62    Male            5          72              86   Pass
62           63    Male            5          80              61   Pass
64           65    Male            5          91              41   Fail
66           67  Female            5          56              81   Fail
69           70  Female            6          97              56   Fail
73           74  Female            5          97              82   Pass
74           75    Male            6          61              87   Fail
76           77  Female            5          86              68   Pass
77           78  Female            6          81              81   Pass
83           84  Female            6          65              52   Fail
84           85    Male            6          52              46   Fail
89           90  Female            6          60              47   Fail
94           95  Female            6          89              90   Pass
97           98  Female            5          97              67   Pass
100         101    Male            6          74              71   Pass
103         104  Female            6          95              90   Pass
104         105  Female            5          67              64   Fail
110         111  Female            6          82              54   Fail
114         115    Male            6          70              47   Fail
119         120    Male            6          52              43   Fail

In [ ]:

p_a = (dataset['Gender'] == 'Male').mean()

p_b = (dataset['Result'] == 'Pass').mean()

p_c = (dataset['Attendance'] > 75).mean()

p_d = (dataset['Previous_Score'] > 70).mean()

p_e = (dataset['Study_Hours'] > 4).mean()


print(f"P(A): {p_a:.4f}")
print(f"P(B): {p_b:.4f}")
print(f"P(C): {p_c:.4f}")
print(f"P(D): {p_d:.4f}")
print(f"P(E): {p_e:.4f}")

P(A): 0.4167
P(B): 0.2250
P(C): 0.4500
P(D): 0.4667
P(E): 0.3000

In [ ]:
# Overall passing probability
p_b = (dataset['Result'] == 'Pass').mean()

# Conditional probabilities
p_b_given_a = dataset.loc[dataset['Gender'] == 'Male', 'Result'].eq('Pass').mean()
p_b_given_c = dataset.loc[dataset['Attendance'] > 75, 'Result'].eq('Pass').mean()
p_b_given_d = dataset.loc[dataset['Previous_Score'] > 70, 'Result'].eq('Pass').mean()
p_b_given_e = dataset.loc[dataset['Study_Hours'] > 4, 'Result'].eq('Pass').mean()

# Quick print comparison
print(f"Overall P(B): {p_b:.2f}")
print(f"P(B|A): {p_b_given_a:.2f}")
print(f"P(B|C): {p_b_given_c:.2f}")
print(f"P(B|D): {p_b_given_d:.2f}")
print(f"P(B|E): {p_b_given_e:.2f}")

Overall P(B): 0.23
P(B|A): 0.22
P(B|C): 0.43
P(B|D): 0.32
P(B|E): 0.44

In [ ]:
import pandas as pd

# Overall passing probability P(B)
p_b = (dataset['Result'] == 'Pass').mean()

# 1. P(B|A) – Probability of Passing given that the student is Male
p_b_given_a = dataset.loc[dataset['Gender'] == 'Male', 'Result'].eq('Pass').mean()

# 2. P(B|C) – Probability of Passing given Attendance > 75%
p_b_given_c = dataset.loc[dataset['Attendance'] > 75, 'Result'].eq('Pass').mean()

# 3. P(B|D) – Probability of Passing given Previous_Score > 70
p_b_given_d = dataset.loc[dataset['Previous_Score'] > 70, 'Result'].eq('Pass').mean()

# 4. P(B|E) – Probability of Passing given Study_Hours > 4
p_b_given_e = dataset.loc[dataset['Study_Hours'] > 4, 'Result'].eq('Pass').mean()

# Print results
print(f"Overall P(B): {p_b:.4f}\n")
print(f"P(B|A) [Pass given Male]: {p_b_given_a:.4f}")
print(f"P(B|C) [Pass given Attendance > 75%]: {p_b_given_c:.4f}")
print(f"P(B|D) [Pass given Previous Score > 70]: {p_b_given_d:.4f}")
print(f"P(B|E) [Pass given Study Hours > 4]: {p_b_given_e:.4f}")

Overall P(B): 0.2250

P(B|A) [Pass given Male]: 0.2200
P(B|C) [Pass given Attendance > 75%]: 0.4259
P(B|D) [Pass given Previous Score > 70]: 0.3214
P(B|E) [Pass given Study Hours > 4]: 0.4444

In [ ]:
import pandas as pd

# Overall passing probability P(B)
p_b = (df['Status'] == 'Pass').mean()

# Conditional probabilities (using df consistently)
p_b_given_a = df.loc[df['Gender'] == 'Male', 'Status'].eq('Pass').mean()
p_b_given_c = df.loc[df['Attendance'] > 75, 'Status'].eq('Pass').mean()
p_b_given_d = df.loc[df['Previous_Score'] > 70, 'Status'].eq('Pass').mean()

# Print comparison
print(f"Overall P(B): {p_b:.4f}\n")
print(f"P(B|A) [Gender]: {p_b_given_a:.4f} (Diff: {abs(p_b_given_a - p_b):.4f})")
print(f"P(B|C) [Attendance]: {p_b_given_c:.4f} (Diff: {abs(p_b_given_c - p_b):.4f})")
print(f"P(B|D) [Previous Score]: {p_b_given_d:.4f} (Diff: {abs(p_b_given_d - p_b):.4f})")

Overall P(B): 0.2250

P(B|A) [Gender]: 0.2200 (Diff: 0.0050)
P(B|C) [Attendance]: 0.4259 (Diff: 0.2009)
P(B|D) [Previous Score]: 0.3214 (Diff: 0.0964)

In [ ]:
import pandas as pd

# Basic probabilities (using df consistently to ensure 'Status' column is available)
p_a = (df['Gender'] == 'Male').mean()
p_b = (df['Status'] == 'Pass').mean()
p_c = (df['Attendance'] > 75).mean()  # P(C) from earlier sections

# 1. P(A ∩ B) – Probability that a student is both Male AND Passes
p_a_and_b = ((df['Gender'] == 'Male') & (df['Status'] == 'Pass')).mean()

# 2. P(A ∩ B) verified using Multiplication Rule: P(A ∩ B) = P(A) % P(B|A)
p_b_given_a = df.loc[df['Gender'] == 'Male', 'Status'].eq('Pass').mean()
p_a_and_b_verified = p_a * p_b_given_a

# 3. P(A ∦ B) – Probability that a student is Male OR Passes (or both)
p_a_or_b = p_a + p_b - p_a_and_b

# 4. Complements
p_not_b = 1 - p_b  # Probability that a student does Not Pass
p_attendance_le_75 = 1 - p_c  # Probability that Attendance is <= 75%

# Print results
print(f"P(A ∩ B): {p_a_and_b:.4f}")
print(f"P(A ∦ B): {p_a_or_b:.4f}")
print(f"Multiplication Check P(A) % P(B|A): {p_a_and_b_verified:.4f}")
print(f"P(Not Pass): {p_not_b:.4f}")
print(f"P(Attendance ≤ 75%): {p_attendance_le_75:.4f}")

P(A ∩ B): 0.0917
P(A ∦ B): 0.5500
Multiplication Check P(A) % P(B|A): 0.0917
P(Not Pass): 0.7750
P(Attendance ≤ 75%): 0.5500